version: 2.1
docker: 
 - image: circleci/node:12
orbs:
  node: circleci/node@1.1.6
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx eyes-storybook
workflows:
    build-and-test:
      jobs:
        - build-and-test
