version: 2.1
docker: 
 - image: circleci/node:12
orbs:
  node: circleci/node@1.1.6
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get install -yq \
            - run: gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2
            - run: libcups2 libdbus-1-3 \
            - run: libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0
            - run: libglib2.0-0 libgtk-3-0 libnspr4 \
            - run: libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1
            - run: libxcb1 libxcomposite1 libxcursor1 \
            - run: libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1
            - run: libxtst6 ca-certificates \
            - run: fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
            - run: npm install
            - run: npx eyes-storybook
workflows:
    build-and-test:
      jobs:
        - build-and-test
